### ISSUE TITLE
Speex Support Inquiry

### ISSUE THREAD

**Issue by mbeacom** [jrottenberg/ffmpeg#10]
@jrottenberg Are you open to a PR introducing the `libspeex` codec?

If so, I'd be happy to submit the PR!

Thank you for the repo!

**Comment by jrottenberg** [comment]
Oh yeah absolutely !

**Comment by mbeacom** [comment]
@jrottenberg That's fine.  I feel that Speex is fairly common in some actionscript fallback cases, but your point is valid.
