### ISSUE TITLE
ubuntu ffmpeg will not build

### ISSUE THREAD

**Issue by adv1023** [jrottenberg/ffmpeg#100]
I try to build and it fails at step 20. I am on ubuntu 16.04.

`Step 20/45 : RUN         DIR=/tmp/opencore-amr &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sL https://10gbps-io.dl.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-${OPENCOREAMR_VERSION}.tar.gz |         tar -zx --strip-components=1 &&         ./configure --prefix="${PREFIX}" --enable-shared  &&         make &&         make install &&         rm -rf ${DIR}
 ---> Running in 67c287050b6d

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
`

**Comment by adv1023** [comment]
I found you on Docker hub. https://hub.docker.com/r/jrottenberg/ffmpeg/~/dockerfile/

**Comment by jrottenberg** [comment]
Yeah it seems related to the tar gz download from sourceforge... 

```
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: datapacket.dl.sourceforge.net

Issuer: Let's Encrypt Authority X3

Expires on: Jun 27, 2018

Current date: Mar 30, 2018
```


It's getting annoying with projects hosted on sourceforge, but yeah they have their artifacts there... Change it to https://kent.dl.sourceforge.net that one seems healthier. I'll update on my side.

**Comment by jrottenberg** [comment]
let's see #101
