### ISSUE TITLE
Use jrottenberg/ffmpeg image as an tool from another Docker Image

### ISSUE THREAD

**Issue by guyhuang** [jrottenberg/ffmpeg#114]
Hi:
I've used  jrottenberg/ffmpeg image as an tool from bash command, code run in bash as follows:
`docker run --rm -v $PWD:/tmp jrottenberg/ffmpeg -stats -ss 10 -t 5 -accurate_seek -i /tmp/source4/1.mp4 -y -codec copy -avoid_negative_ts 1 /tmp/out/cut.mp4`
And it works perfect.

Now I shift my bash command into a docker image, How can I call this same jrottenberg/ffmpeg command? For  jrottenberg/ffmpeg image does not provide a HTTP API.

Thanks.

**Comment by guyhuang** [comment]
After I checked the issues before, I found I can build a new image: replace the frottenberg/ffmpeg docker file from IMAGE with my image.
I'm trying this solution.
When I built this I've got a returned a non-zero code 35.

Here is the FROM phrase.
`FROM        openjdk:8 AS base`

Here is the error message.
`Step 24/46 : RUN         DIR=/tmp/opus &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz &&         echo ${OPUS_SHA256SUM} | sha256sum --check &&         tar -zx --strip-components=1 -f opus-${OPUS_VERSION}.tar.gz &&         autoreconf -fiv &&         ./configure --prefix="${PREFIX}" --enable-shared &&         make &&         make install &&         rm -rf ${DIR} ---> Running in 521c3d92062fThe command '/bin/sh -c DIR=/tmp/opus &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz &&         echo ${OPUS_SHA256SUM} | sha256sum --check &&         tar -zx --strip-components=1 -f opus-${OPUS_VERSION}.tar.gz &&         autoreconf -fiv &&         ./configure --prefix="${PREFIX}" --enable-shared &&         make &&         make install &&         rm -rf ${DIR}' returned a non-zero code: 35`

**Comment by guyhuang** [comment]
I've tried the origanl Dockerfile of jrottenberg/ffmpeg, Also I've got the same error.
Build command:
`docker build --rm -f Dockerfile -t ffmpeg-tool:latest .`

ErrorMessage:
`Step 22/43 : RUN         DIR=/tmp/opus &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz &&         echo ${OPUS_SHA256SUM} | sha256sum --check &&         tar -zx --strip-components=1 -f opus-${OPUS_VERSION}.tar.gz &&         autoreconf -fiv &&         ./configure --prefix="${PREFIX}" --enable-shared &&         make &&         make install &&         rm -rf ${DIR}
 ---> Running in 87cccc17808b
The command '/bin/sh -c DIR=/tmp/opus &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz &&         echo ${OPUS_SHA256SUM} | sha256sum --check &&         tar -zx --strip-components=1 -f opus-${OPUS_VERSION}.tar.gz &&         autoreconf -fiv &&         ./configure --prefix="${PREFIX}" --enable-shared &&         make &&         make install &&         rm -rf ${DIR}' returned a non-zero code: 35`

**Comment by jrottenberg** [comment]
To answer your first question regarding api, ffmpeg doesn't provide a web api, you'll have to build one of top of ffmpeg or use existing opensource project like https://github.com/snickers/snickers/wiki/How-to-Use-the-API

But that image provides ffmpeg only, nothing on top of it.

To get ffmpeg installed in your image, you can use the very nice trick described on https://github.com/jrottenberg/ffmpeg/issues/99#issuecomment-400154614

**Comment by gecube** [comment]
I used @jrottenberg like this:

```
FROM jrottenberg/ffmpeg:4.1-alpine as ffmpeg

FROM python:3.7-alpine3.8

RUN apk add --no-cache --update \
        libgcc \
        libstdc++ \
        ca-certificates \
        libcrypto1.0 \
        libssl1.0 \
        libgomp \
        expat \
        git

COPY --from=ffmpeg /usr/local /usr/local

.... a lot of stuff ....

ENTRYPOINT ["python", "capture_data.py",]```
