### ISSUE TITLE
4.1 images missing on Docker Hub

### ISSUE THREAD

**Issue by qmfrederik** [jrottenberg/ffmpeg#136]
- The 4.1 images have been added to this repo, but are missing on Docker Hub.
- Some of the older tags (3.1, 3.2) are not being updated on Docker Hub. The main impact is that they use outdated versions of the base images.

PS - I've found the builds on quay.io to be faster, should the performance of Docker Hub be an issue.

**Comment by jrottenberg** [comment]
Yeah it's a good idea, I won't switch totally, I'd say dockerhub will eventually build the 4.1, but yeah it makes sense to offer quay as an alternative.

**Comment by jrottenberg** [comment]
Not a big fan of the quey interface, the ui doesn't let me map path to dockerfile to docker tag, making the migration a bit challenging.

There's hope : `New Updates Coming to Docker Hub` let's see, if not I might have to script my way on quay.

**Comment by jrottenberg** [comment]
seems much better now
