### ISSUE TITLE
ffmpeg:vaapi image for a project

### ISSUE THREAD

**Issue by WeiChihChern** [jrottenberg/ffmpeg#144]
Hello,

I'm doing a project that would like to use vaapi for acceleration for vp9 encoding on intel's igpu.  I'm doing development on Mac and having a ubuntu image for running my project.  I wonder does the docker images that have vaapi can be used for development (libs of ffmpeg, h264, h265, vp9)? 

I'm new to docker, how can i get the dockerfile with corresponding tag? (https://hub.docker.com/r/jrottenberg/ffmpeg/dockerfile)  

Thanks,

**Comment by jrottenberg** [comment]
Use https://github.com/videotools/ffmpeg-build it has the development layers
