### ISSUE TITLE
update libvpx to 1.8.0

### ISSUE THREAD

**Issue by Zennoe** [jrottenberg/ffmpeg#148]
A new libvpx version was released a few days ago. I managed to build the container just by changing to `VPX_VERSION=1.8.0`

**Comment by Zennoe** [comment]
Isn't docker supposed to pull Github updates automatically? No new builds since one month ago:
https://hub.docker.com/r/jrottenberg/ffmpeg/builds

**Comment by jrottenberg** [comment]
docker hub is a bit agressive with opensource builds... Those failed with 
```
GoVersion: go1.10.2
Starting build of index.docker.io/jrottenberg/ffmpeg:4.0-centos...
Step 1/48 : FROM centos:7 AS base
Get https://registry-1.docker.io/v2/library/centos/manifests/7: too many requests: too many failed login attempts for username or IP address
```

A retry should fix, on the long run the https://github.com/videotools/ffmpeg-build based image should be much faster to get update

**Comment by jrottenberg** [comment]
can you tell me what variant you are trying to pull @Zennoe ?
