### ISSUE TITLE
rtmps to facebook live

### ISSUE THREAD

**Issue by 3qdev** [jrottenberg/ffmpeg#170]
I try to stream to Facebook live with rtmps

rtmps://live-api-s.facebook.com:443/rtmp/...

```
[tls @ 0x55988f6438c0] error:00000000:lib(0):func(0):reason(0)trate=9033.2kbits/s speed=0.000283x    
av_interleaved_write_frame(): I/O error
[flv @ 0x55988f62d360] Failed to update header with correct duration.
[flv @ 0x55988f62d360] Failed to update header with correct filesize.
Error writing trailer of rtmps://live-api-s.facebook.com:443/rtmp/STREAMKEY: I/O error
frame=   29 fps=0.1 q=-1.0 Lsize=     230kB time=00:00:01.04 bitrate=1804.1kbits/s speed=0.00348x    
video:218kB audio:17kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[tls @ 0x55988f6438c0] error:1409F07F:SSL routines:ssl3_write_pending:bad write retry
    Last message repeated 1 times
Conversion failed!
```
Is there a problem with ssl?

**Comment by jrottenberg** [comment]
weird, which image are you using, can you share the command you are running ?

**Comment by 3qdev** [comment]
i use jrottenberg/ffmpeg:4.1-alpine with

`ffmpeg -copyts -threads 0 -y -re -i rtmp://de-origin-live.3qsdn.com/live/_definst_/mp4:6191_7TZL86ndM2DbgYyFPkQ9_720p -vcodec copy -acodec copy -threads 1 -f flv "rtmps://live-api-s.facebook.com:443/rtmp/663279000797051?s_ps=1&s_sw=0&s_vt=api-s&a=AbwvovLy019TiMFk`

**Comment by 3qdev** [comment]
I think it was a Problem by Facebook, today it works!
