### ISSUE TITLE
Nvidia tags do not exist on docker hub

### ISSUE THREAD

**Issue by huaphuoctruong** [jrottenberg/ffmpeg#177]
The command line to run ffmpeg 4.1 with nvidia acceleration enabled in README does not work anymore due to the 4.1-nvidia tag does not exist on dockerhub.

The command is:

```docker run --runtime=nvidia jrottenberg/ffmpeg:nvidia-4.1 -hwaccel cuvid -c:v h264_cuvid -i INPUT -vf scale_npp=-1:720 -c:v h264_nvenc -preset slow OUTPUT```

**Comment by jrottenberg** [comment]
Yeah the readme is incorrect, will fix, but try ` jrottenberg/ffmpeg:4.1-nvidia`
