### ISSUE TITLE
No such file or directory erro while encoding 

### ISSUE THREAD

**Issue by playmaker420** [jrottenberg/ffmpeg#178]
Hi im trying to encode a video to support  Multi bitrate with Multiple resolutions using the following command. Note:-The file does exist in the location . Thanks in advance

docker run jrottenberg/ffmpeg -i /home/admin/file_example.mp4  -map 0 -map 0 -map 0 -map 0 -c:v libx265 -f dash \
-b:v:0 25M -b:v:1 15M -b:v:2 6M -b:v:3 1M -maxrate 25M -bufsize 1835k -s:v:0 3840x2160 \
-s:v:1 3840x2160 -s:v:2 1920x1080 -s:v:3 1920x1080 -keyint_min 150 -g 150 \  /home/admin/MpegDash/Streams/Clear/Example/4k.mpd 

**Result**

ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
/home/admin/file_example.mp4: No such file or directory

**Other Info**
uname -r
3.10.0-957.5.1.el7.x86_64

**Comment by jeffhoek** [comment]
Looks like you need to map your host volume into the container using `-v` argument.  Something like:
```docker run -v /home/admin/:/temp/ jrottenberg/ffmpeg -i temp/file_example.mp4 -map 0 -map 0 ...```

**Comment by jrottenberg** [comment]
@jeffhoek is correct, another way to do it that could be less confusing is `-v $(pwd):$(pwd)`

so the -i parameter can remain the same.

I'll update the readme, it's a bit confusing the way it is
