### ISSUE TITLE
docker logs -tf  xxx does not show ffmpeg status

### ISSUE THREAD

**Issue by arputcu** [jrottenberg/ffmpeg#18]
docker logs -tf  xxx does not show ffmpeg status
if docker runs in daemon mode
like
frame=  450 fps= 73 q=-1.0 Lsize=    6562kB time=00:00:17.91 bitrate=3000.1kbits/s speed=2.91x
any idea how this can be fixed?

**Comment by jrottenberg** [comment]
interesting !

One thing you could do is to leverage the -progress option
> -progress url       write program-readable progress information

My test case : 
```
docker rm -f $(docker ps -q)
docker run -d  -v $(pwd):/tmp/workdir jrottenberg/ffmpeg -progress  /dev/stdout -y -i trailer_480p.mov -vcodec copy -acodec copy trailer_480p.mkv 
docker logs  -f $(docker ps -q)
```

> ffmpeg version 3.1.3 Copyright (c) 2000-2016 the FFmpeg developers
 [...]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=746
fps=0.0
stream_0_0_q=-1.0
bitrate=1509.7kbits/s
total_size=5853648
out_time_ms=31019000
out_time=00:00:31.019000
dup_frames=0
drop_frames=0
speed=  62x
progress=continue
frame=1470
fps=1469.5
stream_0_0_q=-1.0
bitrate=1510.8kbits/s
total_size=11566738
out_time_ms=61248000
out_time=00:01:01.248000
dup_frames=0
drop_frames=0
speed=61.2x
progress=continue

Try it and let me know, but yeah it would be nice to have that one line repeating line by line out of the box.

**Comment by arputcu** [comment]
perfect, this works fine thx!
