### ISSUE TITLE
Process .mp4 from Azure Blob Storage

### ISSUE THREAD

**Issue by GKotfis** [jrottenberg/ffmpeg#187]
I'm trying to figure it out how to access file from blob storage. Should I mount blob storage as a volume using this https://docs.docker.com/docker-for-azure/persistent-data-volumes/ or maybe there is different approach?
My use case is:
Upload file to dropbox -> Copy to Blob Storage -> Run docker container with ffmpeg -> analyze uploaded file. All is designed using Azure Logic App.

**Comment by jrottenberg** [comment]
Never used it but I'd say if ffmpeg can access it, like a regular on a filesystem it should work fine.

Also that blob storage might exposed a signed url (s3 supports that) so you can access your input file that way.
