### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by coenboomkamp** [jrottenberg/ffmpeg#189]
Hi all,

I think i'm having some permission issues.

This is what i'm trying: I got a camera with rtsp support, and i want to use the rtsp stream as input, and output it in a .jpg file.

I installed ffmpeg with: `docker pull jrottenberg/ffmpeg`

And this is my command:
`sudo docker run jrottenberg/ffmpeg -i 'rtsp://kantoor:password@192.168.2.23/live' -f image2 -vframes 1 -pix_fmt yuvj420p /volume1/Coen\ Boomkamp/Docker/Home\ Automation/FFmpeg/kantoor.jpg`

And here is my output:
`sudo docker run jrottenberg/ffmpeg -i 'rtsp://kantoor:password@192.168.2.23/live' -f image2 -vframes 1 -pix_fmt yuvj420p /volume1/Coen\ Boomkamp/Docker/Home\ Automation/FFmpeg/kantoor.jpgffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://kantoor:password@192.168.2.23/live':
  Metadata:
    title           : Session streamed by "wyze"
    comment         : live
  Duration: N/A, start: 47511.433189, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x24bbac0] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/volume1/Coen Boomkamp/Docker/Home Automation/FFmpeg/kantoor.jpg':
  Metadata:
    title           : Session streamed by "wyze"
    comment         : live
    encoder         : Lavf58.20.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 1920x1080, q=2-31, 200 kb/s, 15 fps, 15 tbn, 15 tbc
    Metadata:
      encoder         : Lavc58.35.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
[image2 @ 0x249eb80] Could not open file : /volume1/Coen Boomkamp/Docker/Home Automation/FFmpeg/kantoor.jpg
av_interleaved_write_frame(): Input/output error
frame=    1 fps=0.0 q=9.3 Lsize=N/A time=00:00:00.06 bitrate=N/A dup=0 drop=4 speed=0.196x    
video:100kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!`

I think its a permission issue because of the `[image2 @ 0x249eb80] Could not open file : /volume1/Coen Boomkamp/Docker/Home Automation/FFmpeg/kantoor.jpg`

I'm quite new with ffmpeg, so bare with me haha. Can anyone point me in the right direction?

Thanks!

**Comment by jrottenberg** [comment]
Paths with spaces are not ideal, but you should be able to use that with `-v $(pwd):$(pwd)` and keep the path you expect. The failure was due to the docker image having no data on those local paths, hence the need to mount as volume (`--volume`)
