### ISSUE TITLE
ffplay is missing

### ISSUE THREAD

**Issue by fitz123** [jrottenberg/ffmpeg#19]
I'm not sure is it intended to be like that or it's disabled by some non-obvious option?

**Comment by jrottenberg** [comment]
Ah ! I don't recall having it enabled in the past. From what it looks like, for the ui part it requires a few system dependencies. I'd rather keep the image small and delegate to the user how to play / validate video (mplayer, vlc, etc)

https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#GettheDependencies

> Note: Server users can omit the ffplay and x11grab dependencies: libsdl1.2-dev libva-dev libvdpau-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev.
