### ISSUE TITLE
Support for x11grab

### ISSUE THREAD

**Issue by matthewcoyle-cpc** [jrottenberg/ffmpeg#195]
I'm attempting to write a docker container based on ffmpeg which can headlessly display a gui application to a virtual display (with Xvfb) and record the display to a gif
It seems that this isn't possible with current version of the ffmpeg docker images (Unknown input format: 'x11grab')

Do you think this would/could be supported by the current images or a custom image?

**Comment by jrottenberg** [comment]
hello !


I didn't know that option, pretty nice 
https://trac.ffmpeg.org/wiki/Capture/Desktop
https://ffmpeg.org/ffmpeg-devices.html#x11grab

It might be a bit more than just adding libxcb, you might have to tweak the docker run options to mount but yeah doable : https://gist.github.com/kfei/ef3c7fb7d4101f7dc537

Happy to merge if you want to add support for x11grab in this image.
