### ISSUE TITLE
Does'n work converting on MP4 container

### ISSUE THREAD

**Issue by wilful** [jrottenberg/ffmpeg#20]
Have a command like:

`docker run jrottenberg/ffmpeg -stats -i http://url/file.mp4 -b 640k -c:v libx264 -profile:v high -preset medium -f mp4 - > /tmp/out.mp4`

On output i have:
```
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
[libx264 @ 0x2ef8b20] final ratefactor: 24.75
[aac @ 0x2e65f80] Qavg: -nan
```

You have not encountered a similar problem for the mp4 container?
i found http://superuser.com/questions/760056/receiving-ffmpeg-error-22-when-piping-data-to-stdout

**Comment by jrottenberg** [comment]
I might depend on your input file, is it possible to put it online, or if not a clip from it using the same format ?

Also could you try with another version of ffmpeg, no through my image (on a mac the homebrew version for example), to see if it's a ffmpeg limitation or a flag I"m not passing to mine.

**Comment by jrottenberg** [comment]
Interesting discussion here http://thread.gmane.org/gmane.comp.video.ffmpeg.user/40419

I'll close the issue as it is not strictly related to ffmpeg on docker but more on ffmpeg + mp4 output.
