### ISSUE TITLE
enable bluray support

### ISSUE THREAD

**Issue by 1000010** [jrottenberg/ffmpeg#200]
current configuration of ffmpeg build does not enable bluray as source (i.e. '-i bluray:...'). configuration needs to be updated with: --enable-libbluray

**Comment by git-developer** [comment]
Seems to be fixed by #212, at least I'm able to use `-i bluray:`... on `ffprobe` of image `ffmpeg:4.2-vaapi`

**Comment by tyranron** [comment]
ping @jrottenberg 

Seems to be resolved.
