### ISSUE TITLE
How to output chunks & m3u8 playlist to host?

### ISSUE THREAD

**Issue by stefanheimann** [jrottenberg/ffmpeg#201]
Hello,

I try to encode video from any format to hls streaming, how can I get the chunks and m3u8 playlist back to the host? I'm running the following command (simplyfied):

`
docker run jrottenberg/ffmpeg:latest \
    -stats -hide_banner -y \
    -i http://www.jell.yfish.us/media/jellyfish-20-mbps-hd-hevc-10bit.mkv \
    -hls_time 4 \
    -hls_playlist_type vod \
    -hls_segment_filename encoding_%03d.ts encoding.m3u8
`

ffmpeg is working an creating the files, but they are only in the container, how can I get them onto the host system?

**Comment by jidckii** [comment]
Hi,
you can mount directory from host to container, use option `-v `
https://docs.docker.com/storage/bind-mounts/
```
mkdir ~/tmp
cd ~/tmp
docker run --rm -it \
-v $PWD:/tmp/workdir \
jrottenberg/ffmpeg:latest \ 
-hide_banner -y \ 
-i http://www.jell.yfish.us/media/jellyfish-20-mbps-hd-hevc-10bit.mkv \ 
-hls_time 4 \ 
-hls_playlist_type vod \ 
-hls_segment_filename "encoding_%03d.ts" \
encoding.m3u8
```
if you need use `-hls_playlist_type live` i recommend use mount into tmpfs, for save disk

**Comment by stefanheimann** [comment]
Thanks @jidckii totally right.
Just for reference if somebody is working on windows like me, for the mount you've to use
`-v "/$(pwd -W):/tmp/workdir"`
