### ISSUE TITLE
recommended to use the http protocol to "curl" files

### ISSUE THREAD

**Issue by highsea** [jrottenberg/ffmpeg#202]
https://github.com/jrottenberg/ffmpeg/blob/d7c55654405643e6f074e949d0c31d72dd7188b6/docker-images/4.2/alpine/Dockerfile#L84

https://github.com/jrottenberg/ffmpeg/blob/d7c55654405643e6f074e949d0c31d72dd7188b6/docker-images/4.2/alpine/Dockerfile#L191

The certificate of this domain name has expired, causing the file obtained by curl to be abnormal. 

```bash
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now

# https -> http
curl -sL http://versaweb.dl.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-${OPENCOREAMR_VERSION}.tar.gz | \
```

**Comment by jrottenberg** [comment]
I'd stick to https,  it seems back now but that's annoying... 

I'd go with the tarball of the tags but https://sourceforge.net/p/opencore-amr/code/ci/v0.1.5/tarball doesn't make it easy.

Not sure why lame and opencore-amr are on sourceforge, definitely a challenge to integrate.

**Comment by fiftysoft** [comment]
i fix it by add -k to curl

           curl -sL -k https://kent.dl.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-${OPENCOREAMR_VERSION}.tar.gz
