### ISSUE TITLE
Enable AOM (AV1) on centos

### ISSUE THREAD

**Issue by ernado** [jrottenberg/ffmpeg#219]
Seems like there is no `--enable-libaom` on centos for some reason.

**Comment by ernado** [comment]
For anyone trying to build aom on centos, you can try this:
```Dockerfile
## aom
RUN \
	DIR=/tmp/aom && \
        git clone --branch ${AOM_VERSION} --depth 1 https://aomedia.googlesource.com/aom ${DIR} && \
        rm -rf CMakeCache.txt CMakeFiles && \
        cd ${DIR} && \
        mkdir -p ./aom_build && \
        cd ./aom_build && \
        cmake -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DBUILD_SHARED_LIBS=1 .. && \
        make -j$(nproc) && \
        make install
```

Note `DCMAKE_INSTALL_LIBDIR="lib"` which is required to install to `/opt/ffmpeg/lib` instead of `/opt/ffmpeg/lib64`.

This option can fix the following error:
```
ERROR: aom >= 1.0.0 not found using pkg-config 
```

**Comment by jrottenberg** [comment]
interesting !

yeah centos never had aom in our image : https://github.com/jrottenberg/ffmpeg/commit/5fd29bda1b3703243993407458ee94f5a1ee9d6b
>  remove aom for centos7 since it's doesn't have the build tool required

but your workaround looks promising

**Comment by ernado** [comment]
Also the Centos version is bumped to 8, so probably the build tool is already here (but I'm not sure what tool exactly). 

AFAIK libaom is still in Dockerfile, but just not linked:
https://github.com/jrottenberg/ffmpeg/blob/23c16671466d777ae4d27a5c5b41b288902fd88c/docker-images/4.2/centos/Dockerfile#L322-L332

**Comment by hvindin** [comment]
@ernado if you want to try the latest centos8 (or even the centos7)  containers libaom should be available.

**Comment by ernado** [comment]
Thank you!
