### ISSUE TITLE
ZeroMQ support

### ISSUE THREAD

**Issue by tyranron** [jrottenberg/ffmpeg#229]
At the moment this Docker image doesn't ship with `libzmq` and `--enable-libzmq` compiled. However, I miss it quite much for on-fly FFmpeg filters adjusting and have to copy-paste the whole `Dockerfile` and add ZeroMQ support in there.

If image authors don't mind, I'd like to PR support for `libzmq` and `zmqsend` tool.

**Comment by jrottenberg** [comment]
That seems doable, are you interested doing it ?


It should be straightforward (?)

**Comment by tyranron** [comment]
@jrottenberg would you be so kind to kick failing builds in `master` to restart? I need `4.2-centos7` and it's not on Docker Hub, unfortunately.

**Comment by jrottenberg** [comment]
https://dev.azure.com/video-tools/ffmpeg/_build/results?buildId=283&view=results 🤞
