### ISSUE TITLE
Breaking changes in tag ffmpeg:4.2-nvidia

### ISSUE THREAD

**Issue by givo** [jrottenberg/ffmpeg#232]
Hi Jrottenberg,

First of all I'd love to thank you on your amazing work on this great repository, it's life saving work, you are the best!

Recently you added some [breaking changes](https://github.com/jrottenberg/ffmpeg/commit/109502c17a6baa8811d2800aedc4344c8189fe65#diff-9e6cad229b114cee58ea41f5cd5c05e3) to the tag `ffmpeg:4.2-nvidia` by updating CUDA from 9.2 to 10.2. It resulted in breaking my newest builds that I'm running on machines with older GPUs that don't support CUDA 10.2.
The problem is that you override the tag `ffmpeg:4.2-nvidia` with a new version but the tag stays unchanged. 

I think it would be really helpful if you will add another indication in the tag for the CUDA version, something like:

`ffmpeg:4.2-nvidia-cuda10.2`

And bring back a version of Cuda 9.2?

What do you think?

Thanks again :)

**Comment by jrottenberg** [comment]
Thank you ! And sorry to hear about that regression, it sucks. I'm having a bit too many variants at the moment, definitely makes everything a bit slower to run/validate.

I can make a tag of 9.2 to help, but the real solution is to build aliases, so it's not just rolling forward releases.

**Comment by givo** [comment]
Thank you very much for responding :)

I hear you, and I appreciate your time and effort, and understand the

**Comment by jrottenberg** [comment]
`docker pull jrottenberg/ffmpeg:4.2-nvidia-cuda9.2` should do the trick it comes from

https://github.com/jrottenberg/ffmpeg/blob/nvidia/cuda/9.2/docker-images/4.2/nvidia1804/Dockerfile

**Comment by givo** [comment]
Thank you very much!
