### ISSUE TITLE
Cannot load libcuda.so.1

### ISSUE THREAD

**Issue by kuznetcoff777** [jrottenberg/ffmpeg#233]
FROM jrottenberg/ffmpeg:4.2-nvidia

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-nvenc --enable-cuda --enable-cuvid --enable-libnpp --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/'

When i try to ffmpeg with -c:v h264_nvenc  i got thie problem. Strange, cause ffmpe built up with nvenc/cude/cuvid support. File exists in /usr/local/cuda-10.2/compat/libcuda.so.1

How to resolve issue?

**Comment by kuznetcoff777** [comment]
Seems to be that problem related to that in composer no gpu was described
when i try to run 
docker run --runtime=nvidia 
docker run --gpus all 
then it works.

But how to run service with that gpu enabled?

**Comment by wobeng** [comment]
@kuznetcoff777 were you able to fix this?

**Comment by kuznetcoff777** [comment]
@wobeng 

https://docs.docker.com/compose/gpu-support/

```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

```
