### ISSUE TITLE
Add libaribb24 ARIB STD-B24 caption decoder suport

### ISSUE THREAD

**Issue by plainbanana** [jrottenberg/ffmpeg#254]
Since ffmpeg 4.2, [libaribb24](https://ffmpeg.org/ffmpeg-all.html#libaribb24) is supported. This makes it possible to handle subtitle data in Japanese television broadcasting according to ARIB STD-B24 of Profile A and C.

It's a feature that may not be appropriate to create as PR because that is only used in limited situations, but if authors do not mind, I would like to support `libaribb24`.

**Comment by jrottenberg** [comment]
thank you very much !

**Comment by plainbanana** [comment]
Thank you for Merge!
