### ISSUE TITLE
Getting 'Connection Reset By Peer' errors when using the image on ec2

### ISSUE THREAD

**Issue by simonavril** [jrottenberg/ffmpeg#26]
While streaming to an FB rtmp for FB live my stream gets randomly interrupted after a while with a connection reset by peer.

Probably not the image's fault but a network issue and just was curious to see that no-one reported the issue. There might be a workaround possible with the image I am not sure yet.

**Comment by jrottenberg** [comment]
Hello !


Can't say I was able to reproduce, my workflow involve more s3 as source for a stream than FB live.
If you could provide an example command, so I can try to reproduce.

**Comment by simonavril** [comment]
Thanks!

Sorry the example command might be tricky. But what I meant is use a local source sent to a fb live stream (a live video "object" needs to be created first through the api and they return a rtmp url one can send data to)

I noticed that I had much better results installing ffmpeg straight onto the machine without using docker but because it is so random and unpredictable it might be a red herring. 

Thanks a lot for this image anyways it got me going for a long time and was really useful.
