### ISSUE TITLE
I wonder if missing .tar.gz suffix in dockerfile

### ISSUE THREAD

**Issue by lanxiuying** [jrottenberg/ffmpeg#264]
`https://versaweb.dl.sourceforge.net/project/lame/lame/$(echo ${LAME_VERSION}`
I guess there should be 
`https://versaweb.dl.sourceforge.net/project/lame/lame/$(echo ${LAME_VERSION}.tar.gz`
![image](https://user-images.githubusercontent.com/16331579/92596204-0fca5f00-f2d8-11ea-8763-580ee91c9490.png)
[https://hub.docker.com/r/jrottenberg/ffmpeg/dockerfile](url)

**Comment by jrottenberg** [comment]
it's s a very long line : 

```
        curl -sL https://versaweb.dl.sourceforge.net/project/lame/lame/$(echo ${LAME_VERSION} | sed -e 's/[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)/\1.\2/')/lame-${LAME_VERSION}.tar.gz | \
tar -zx --strip-components=1 

```

but yeah it gets the tar.gz
