### ISSUE TITLE
Hardware acceleration support ?

### ISSUE THREAD

**Issue by lamarios** [jrottenberg/ffmpeg#27]
Hi,

Does this container supports hardware acceleration like intel quicksync ?

**Comment by jrottenberg** [comment]
Not at the moment, I'm looking at it : https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by mcelhennyi** [comment]
+1 for hardware accel support

**Comment by jrottenberg** [comment]
closing since we have a vaapi variant.
