### ISSUE TITLE
latest-vaapi2004 builds using ubuntu 1604 instead of ubuntu 2004

### ISSUE THREAD

**Issue by eikowagenknecht** [jrottenberg/ffmpeg#271]
Using the current (today) latest-vaapi2004 build I get the following result:

`built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609`

![image](https://user-images.githubusercontent.com/1475672/103130159-d0aff600-469b-11eb-9ff4-805b7348c6a1.png)

Using for example latest-ubuntu2004 instead seems to be correct:

`built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04):`

![image](https://user-images.githubusercontent.com/1475672/103130213-05bc4880-469c-11eb-8893-9b24a789b190.png)

This leads to me getting the error message `ffmpeg: error while loading shared libraries: libva.so.1: cannot open shared object file: No such file or directory` when trying to run the latest-vaapi2004 build (which in reality is a ubuntu 1604 build) on a ubuntu 2004 based image.

**Comment by eikowagenknecht** [comment]
Seems to be caused by https://github.com/jrottenberg/ffmpeg/commit/82bac4d4446bd90c9c69ab4de93ceb626683f4e7 where 1804 was renamed to 2004 and 1604 instead was written into the Dockerfile (together with an old libva):

![image](https://user-images.githubusercontent.com/1475672/103130741-3d2bf480-469e-11eb-92b5-e0ff7913d1ff.png)

**Comment by jrottenberg** [comment]
Nice catch, let's see...

**Comment by eikowagenknecht** [comment]
Thanks for the merge 👍

**Comment by eikowagenknecht** [comment]
@jrottenberg Can you please also update / rerun the dockerhub builds? The current version is 8 days old and so doesn't work yet.

![image](https://user-images.githubusercontent.com/1475672/103296074-92953800-49f5-11eb-94a8-582c6f2b598c.png)

**Comment by eikowagenknecht** [comment]
@jrottenberg Could you please check? I still can't see it on dockerhub;

![image](https://user-images.githubusercontent.com/1475672/104284603-92e00980-54b2-11eb-8d56-3cf5e9686548.png)

**Comment by eikowagenknecht** [comment]
Tried to fork the repo to build this myself. Aaaaand the build fails at this step:

```
Configuring tzdata
------------------
Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.
1. Africa 4. Australia 7. Atlantic 10. Pacific 13. Etc
2. America 5. Arctic 8. Europe 11. SystemV
3. Antarctica 6. Asia 9. Indian 12. US
Geographic area:
Build canceled.
```

Seems like it's waiting for user input that never happens. Will try to fix this with

```
# FIX FOR tzdata interactivity
ENV     DEBIAN_FRONTEND=noninteractive
RUN     apt-get -y install tzdata
```

at the beginning of the Dockerfile. Will report if it helps.

**Comment by jrottenberg** [comment]
Right I believe it is the correct fix. There was a merge request that was adding that line that I had blocked because there was another way to solve the issue (avoid pulling tzdata) but I regret it now.

Thank you for following up, once the pipelines pass I'll merge.

**Comment by eikowagenknecht** [comment]
Hey @jrottenberg The PR #280 can be merged, only snapshot is failing and this is because of an unrelated error :-)

**Comment by eikowagenknecht** [comment]
While I was on it I fixed all the other build issues as well.. see #283. Can be merged now.
