### ISSUE TITLE
Stream issue in docker container

### ISSUE THREAD

**Issue by sdzbxiayu** [jrottenberg/ffmpeg#277]
Hi,
I meet a problem which seems multicast ts can't go in or out the container. In the container I can't receive any multicast ts from outside. But I can stream same multicast TS on my host machine. Following is the test I have done:

1. check the firewall of container and realize firewall is not installed at all.
2. check the udp communication between host machine and container by nc. It's working.
3. run a container and generate a multicast ts. but can't probe it on host machine or another container which is in the same docker network.

host_machine# docker run -it --name container1 --entrypoint="bash" --network=docker_network jrottenberg/ffmpeg:centos
container1# ffmpeg -re -stream_loop -1 -i /test.ts -f mpegts udp://233.3.3.3:4433
host_machine# docker run -it --name container2 --entrypoint="bash" --network=docker_network jrottenberg/ffmpeg:centos
container2# ffprobe -i udp://233.3.3.3:4433
host_machine# ffprobe -i udp://233.3.3.3:4433

Any clues? Thanks in advance

**Comment by jrottenberg** [comment]
Even if it's a shared network I'm pretty sure the port needs  to be published, on the second container run command add :

` -p 4443:4443/udp`


```
host_machine# docker run -it --name container2 -p 4443:4443/udp --entrypoint="bash" --network=docker_network jrottenberg/ffmpeg:centos
```

**Comment by sdzbxiayu** [comment]
Thanks. I can probe the container1's stream from container2 after container2's 4433 port published.

Now the question is what should I do if I want to probe a stream from ourside host machine. I can probe ourside stream(udp://226.3.3.4:4252) from host_matchine after firewall stop. But I can't probe it in the container with port 4252 published.

host_machine#ffprobe -i udp://226.3.3.4:4252
host_machine#docker run -it --name container1 -p 4252:4252/udp --entrypoint="bash" --network=docker_network jrottenberg/ffmpeg:centos
container2#ffprobe -i udp://226.3.3.4:4252

**Comment by sdzbxiayu** [comment]
Also I tried this. udp://226.3.3.4:4252 is from outside of host machine and can be detect by the ffmpeg on host machine, but not by the container.

**[root@localhost ~]# docker run -p 4252:4252/udp jrottenberg/ffmpeg:centos -i udp://226.3.3.4:4252 -f mpegts udp://234.2.3.4:1234
ffmpeg version 3.4.5 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-postproc --enable-small --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100**

**Comment by sdzbxiayu** [comment]
Problem solved. Container network needs to be set to host type. In bridge type, it seems only stream with specific destination ip can go inside container.

**docker run --net=host jrottenberg/ffmpeg:centos -i udp://226.3.3.4:4252 -f mpegts udp://234.2.3.4:1234**

**Comment by jrottenberg** [comment]
ah !

🦆  https://en.wikipedia.org/wiki/Rubber_duck_debugging

You're welcome !
