### ISSUE TITLE
**apk** is missing in image

### ISSUE THREAD

**Issue by zxkane** [jrottenberg/ffmpeg#28]
```sh
docker run --rm -it --entrypoint=/bin/sh jrottenberg/ffmpeg
# which apk
# 
```

**Comment by jrottenberg** [comment]
What tag are you using ? version of the image ?

**Comment by zxkane** [comment]
Looks like the image with latest tag was built from ubuntu. I got wrong assumption from the [dockerfile](https://hub.docker.com/r/jrottenberg/ffmpeg/~/dockerfile/) listed in docker hub.
