### ISSUE TITLE
How to copy files out to Windows Host

### ISSUE THREAD

**Issue by f135ta** [jrottenberg/ffmpeg#288]
I'm pretty new to Docker; but i've managed to get your container running and produce an output (see image) in the container.

I'm running your container on a Windows Host, and want to be able to output the files directly into a Windows directory as it produces them. Is that possible? If so, can you let me know how please?

![image](https://user-images.githubusercontent.com/2043562/112769240-e379f400-9017-11eb-8254-4aeca5dc6ddf.png)

**Comment by f135ta** [comment]
No worries - i've solved it.. I was missing the following from the Docker Run command:

`-v d:\streams:/tmp/workdir`

I'll post it here incase anyone else has the same question ;-)

**Comment by jrottenberg** [comment]
Thank you for posting the command that worked for you. Yeah mounting the volume is necessary, but never done it on windows , nice to see how it works.
