### ISSUE TITLE
Unused flag "MAKEFLAGS"

### ISSUE THREAD

**Issue by Xantios** [jrottenberg/ffmpeg#311]
in the dockerfile the variable "MAKEFLAGS" is defined (default with "-j2") changed it out to "-j24") but the variable is defined and never used?

anything Im missing here?

**Comment by bstivers** [comment]
I know this is old. You've probably figured it out by now. But I figured I would reply anyway. 

It's a [docker build argument](https://docs.docker.com/engine/reference/builder/#arg) for an environment variable that can be changed during `docker build`.
e.g. `docker build MAKEFLAGS="-j24" -f Dockerfile .`

There's no need to change it within the main `Dockerfile`

The environment variable is automatically picked up by all `make` commands as if it were entered in as `make -j24`. 

reference: [5.7.3 Communicating Options to a Sub-make](https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html)
