### ISSUE TITLE
nvidia2004 4.4 is using 1804 image to build

### ISSUE THREAD

**Issue by cowmix** [jrottenberg/ffmpeg#314]
https://github.com/jrottenberg/ffmpeg/blob/master/docker-images/4.4/nvidia2004/Dockerfile#L9

If I switch it out, ffmpeg doesn't build.

Here's the error on rebuild:

Step 70/80 : RUN         DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-shared         --enable-avresample         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-gpl         --enable-libass         --enable-fontconfig         --enable-libfreetype         --enable-libvidstab         --enable-libmp3lame         --enable-libopus         --enable-libtheora         --enable-libvorbis         --enable-libvpx         --enable-libwebp         --enable-libxcb         --enable-libx265         --enable-libxvid         --enable-libx264         --enable-nonfree         --enable-openssl         --enable-libfdk_aac         --enable-postproc         --enable-small         --enable-version3         --enable-libbluray         --enable-libzmq         --extra-libs=-ldl         --prefix="${PREFIX}"         --enable-libopenjpeg         --enable-libkvazaar         --enable-libaom         --extra-libs=-lpthread         --enable-libsrt         --enable-libaribb24         --enable-nvenc         --enable-cuda         --enable-cuvid         --enable-libnpp         --extra-cflags="-I${PREFIX}/include -I${PREFIX}/include/ffnvcodec -I/usr/local/cuda/include/"         --extra-ldflags="-L${PREFIX}/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib32/" &&         make &&         make install &&         make tools/zmqsend && cp tools/zmqsend ${PREFIX}/bin/ &&         make distclean &&         hash -r &&         cd tools &&         make qt-faststart && cp qt-faststart ${PREFIX}/bin/
 ---> Running in 8eee3942b8e0
ERROR: libnpp not found

**Comment by csreynolds** [comment]
Add the ENV line from my comment here:

https://github.com/jrottenberg/ffmpeg/issues/294#issuecomment-866809958
