### ISSUE TITLE
Adding Chromaprint

### ISSUE THREAD

**Issue by geoffjukes** [jrottenberg/ffmpeg#324]
Hi,

In reference to https://github.com/jrottenberg/ffmpeg/issues/247#issuecomment-660227824 I didn't see a ticket for adding Chromaprint - so I'm doing the honors :)

All the best,

Geoff

**Comment by jrottenberg** [comment]
Ah ! ;-)

Now that there is an issue... I'll check this weekend 🤞

**Comment by geoffjukes** [comment]
Fantastic!

I took a stab at it today, and hit an issue with FontConfig on Ubuntu 20.04. It felt a little catch-22, Chromaprint wants FFMpeg, which wants libchromaprint1

I tried compiling it from source, copying the pattern you established for the other 3-rd part libraries (rather than just apt installing it). That didn't even work, because of FOntConfig.

I'm wondering if I should try to compile the fpcalc version.... but I'm so far out of my comfort zone now, I'm not even sure which way is up.

I'm sure it will all make much more sense to you :)

Some (maybe) helpful links for you:

https://github.com/acoustid/chromaprint
https://github.com/acoustid/chromaprint-build-base

**Comment by jrottenberg** [comment]
Right not super fun : chromaprint needs a vanilla ffmpeg built, and ffmpeg needs chromaprint deployed to `--enable-chromaprint`

I've tried to do exactly that, not sure it's satisfying but it passes, mostly : #325 .

I'll check the compiled version of chromaprint to break the chicken-egg

**Comment by jrottenberg** [comment]
Yeah we're not the only one suffering from it : https://bugs.gentoo.org/625210#c5

**Comment by jrottenberg** [comment]
The builds are coming @geoffjukes give it a try once pushed https://dev.azure.com/video-tools/ffmpeg/_build/results?buildId=478&view=results

**Comment by geoffjukes** [comment]
Amazing @jrottenberg! Thank you for grinding through. I'll be testing this out today.

**Comment by simonv3** [comment]
It looks like this didn't make it into 5.1+?
