### ISSUE TITLE
FFmpeg Release 6 Support

### ISSUE THREAD

**Issue by ImVexed** [jrottenberg/ffmpeg#365]
http://www.ffmpeg.org/download.html#release_6.0

**Comment by kuznetcoff777** [comment]
@jrottenberg If 6 version will be also be available?

**Comment by jrottenberg** [comment]
oh nice catch, I'll add the rolling tag

**Comment by kuznetcoff777** [comment]
It will be more helpful if vmaf also be included) just in casae

**Comment by Commandcracker** [comment]
This issue should be closed because zmwangx/rust-ffmpeg-sys#50 is merged!
