### ISSUE TITLE
Upgrade ubuntu images to 22.04 (LTS)

### ISSUE THREAD

**Issue by superflyxxi** [jrottenberg/ffmpeg#366]
Request to have docker images for ubuntu and vaapi to use latest LTS version of ubuntu (22.04)

**Comment by simoncrowe** [comment]
I can second this. It's a bit of a blocker for anyone who needs to upgrade from the deprecated OpenSSL 1.1 to 3.

**Comment by jrottenberg** [comment]
Hello !


I need to get a second look at https://github.com/jrottenberg/ffmpeg/pull/375/files

That was the intent (refresh base image) but it broke ;-/

**Comment by geosigno** [comment]
Any update?

**Comment by james-hu** [comment]
It seems the build for ubuntu2204_6.1.1 succeeded. I see hope.
I think most of the people will be interested in trying newer version of ffmpeg on newer version of Ubuntu.

**Comment by jrottenberg** [comment]
in progress https://github.com/jrottenberg/ffmpeg/pull/385

**Comment by james-hu** [comment]
Thank you @jrottenberg ! I can see those images are available on hub.docker.com. Can we consider them as "released"?

**Comment by jrottenberg** [comment]
absolutely #385 has been merged
