### ISSUE TITLE
Question: Is there / can there be a build for linux with video toolbox included?

### ISSUE THREAD

**Issue by Junto026** [jrottenberg/ffmpeg#368]
I am using docker for my conversions on a MacOS host, hoping to leverage hardware acceleration.

**Comment by ttyS0** [comment]
Docker on macOS is running in a Linux VM, and macOS hardware like media encoder engines doesn't get passed through. Your best bet is to use `ffmpeg` natively on macOS to use video toolbox.

**Comment by Junto026** [comment]
Makes sense why I could find it in the ffmpeg builds for MacOS but none of the builds for Linux had it.  I was hoping there'd still be a way to pass through to the linux VM to do it.  Thanks for the answer!
