### ISSUE TITLE
gpg: keyserver timed out

### ISSUE THREAD

**Issue by kianxineki** [jrottenberg/ffmpeg#39]
```
gpg: requesting key D67658D8 from hkp server ha.pool.sks-keyservers.net
gpg: keyserver timed out
```
He tried to use the version 3.3 Dockerfile and I get this error, tried a change ha.pool.sks-keyservers.net by pool.sks-keyservers.net and it works correctly

**Comment by jrottenberg** [comment]
oh ! let me test locally.
