### ISSUE TITLE
add --enable-libass

### ISSUE THREAD

**Issue by ryugate** [jrottenberg/ffmpeg#40]
Thank you for excelent image for ffmpeg.

I want to use -vf ass option to burn ass subtitle.
Please add --enable-libass when exec coufigure command.

best regard.

**Comment by jrottenberg** [comment]
seems doable : https://unix.stackexchange.com/questions/116036/how-to-enable-libass-on-linux
I'll have a look.

**Comment by jrottenberg** [comment]
#50 should address it , let us know (thanks again @GnaphronG !) otherwise.

**Comment by ryugate** [comment]
Thank so much!!!

But this image had no fonts, so I wrote a small Dockerfile like that to install a font I need.
-----
FROM jrottenberg/ffmpeg

RUN apt-get update
RUN apt-get install fonts-takao-pgothic
-----
Finally, I can make a movie with captions. :)

Thank you!
