### ISSUE TITLE
Pipe output to stdout

### ISSUE THREAD

**Issue by marcuslindblom** [jrottenberg/ffmpeg#45]
How can I pipe the generated image from this command to stdout?

`-i https://s3-eu-west-1.amazonaws.com/.../original.mp4 -c:a copy -f mjpeg -preset ultrafast -an -c:v mjpeg -vf \"select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50\" -q:v 20 -vframes 1`

**Comment by jrottenberg** [comment]
Look at the example : https://github.com/jrottenberg/ffmpeg#example

Basically end your command with a dash :

```
docker run jrottenberg/ffmpeg -i https://s3-eu-west-1.amazonaws.com/.../original.mp4 -c:a copy -f mjpeg -preset ultrafast -an -c:v mjpeg -vf \"select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50\" -q:v 20 -vframes 1 -   >  out.mp4```

**Comment by marcuslindblom** [comment]
@jrottenberg It seems to work with `pipe:1`?

**Comment by jrottenberg** [comment]
Oh I see, yet let me see.

**Comment by jrottenberg** [comment]
Ah actually nevermind, a pipe is a pipe :

```docker run jrottenberg/ffmpeg:3.3-alpine  -stats  -i http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_2mb.mp4   -c:a copy -f mjpeg -preset ultrafast -an               -c:v mjpeg -vf "select='not(mod(n\\,29))',yadif,scale=480:-1,crop=iw:270,tile=1x50"                         -q:v 20 -vframes 1     -   >  out.mp4```

Note the unescaped option for the vf.
