### ISSUE TITLE
-vf subtitles doesn't work (because no fonts are installed)

### ISSUE THREAD

**Issue by dandelionred** [jrottenberg/ffmpeg#51]
b892353741510db29baa85c04a6cd12be8c4dc6f introduced support for libass, but there is no /usr/share/fonts dir at all so the feature just doesn't work.

**jrottenberg/ffmpeg:3.3-alpine** image:
```
/ $ ls -l /usr/share/
total 12
drwxr-xr-x    3 root     root          4096 Jul 30 18:23 ca-certificates
drwxr-xr-x    2 root     root          4096 Jun 25 17:52 man
drwxr-xr-x    2 root     root          4096 Jun 25 17:52 misc
/ $
```

Adding `ttf-liberation` package to the image makes it possible to render subs into video.

**Comment by jrottenberg** [comment]
ah, yeah let's see

**Comment by GnaphronG** [comment]
I mounted a folder with my font with -v $PWD/fonts:/usr/share/fonts to test, so i can choose the fonts and keep the image small.

**Comment by dandelionred** [comment]
@GnaphronG You _can_ do that but currently the feature looks like is it broken out of the box. Let there better be a small font package inside the image so it just **works by default**.

**Comment by dandelionred** [comment]
@GnaphronG Also please notice while the image has `libfontconfig` installed, ffmpeg configure option `--enable-libfontconfig` is not set. I guess that's why `-vf drawtext=font=XX...` gives me this
```
[Parsed_drawtext_1 @ 0x5641f7cdd740] Option 'font' not found
[AVFilterGraph @ 0x5641f7cdd180] Error initializing filter 'drawtext' with args 'text=test:font=Liberation:x=lh:y=lh:fontsize=12:box=1:boxborderw=2'
Error reinitializing filters!
Failed to inject frame into filter network: Option not found
Error while processing the decoded data for stream #0:0
Conversion failed!
```

It only works if I give it `fontfile=YY` option.

**Comment by ryugate** [comment]
I solved this problem in the following way.
I made a small Dockerfile like that to install a font I need and made a new image.

-----

FROM jrottenberg/ffmpeg

RUN apt-get update
RUN apt-get install fonts-takao-pgothic

-----

Just for your information...

**Comment by jrottenberg** [comment]
yeah that makes sense so at least you have control on the font you get.

`RUN apt-get update && apt-get install fonts-takao-pgothic`
