### ISSUE TITLE
Suggest to use "apk add --no-cache" in alpine

### ISSUE THREAD

**Issue by trickkiste** [jrottenberg/ffmpeg#52]
It might not actually make a difference in your setup, as you are clearing caches in your last line anyways, but there is the `apk add --no-cache` switch, which you could use to prevent caches from being created in the first place.

Great work!
My best regards,
Markus

**Comment by jrottenberg** [comment]
Oh that's nice ! I'm not using alpine that works but that seems like a sensible thing to do on https://github.com/jrottenberg/ffmpeg/blob/master/Dockerfile-template.alpine#L37

commit

run ./update.py

commit 


Merge request, i'll take it with pleasure !

**Comment by GnaphronG** [comment]
Added in #58 for the Alpine build
