### ISSUE TITLE
optimise speed instead of size?

### ISSUE THREAD

**Issue by srnm** [jrottenberg/ffmpeg#7]
I don't know what difference this makes in practice, but please consider building this image for speed instead of size?

  --enable-small           optimize for size instead of speed

Thanks!

**Comment by jrottenberg** [comment]
Just checked, it seems to be the case already since the early age of this project, at least for ffmpeg itself : 
https://github.com/jrottenberg/ffmpeg/blob/83b5ab65972de162e525e4ac29d10f3ffc67fe9f/run.sh#L76

**Comment by srnm** [comment]
I was unclear -- I was asking if you could *remove* --enable-small ...
