### ISSUE TITLE
Fribidi won't compile anymore

### ISSUE THREAD

**Issue by rsdrsd** [jrottenberg/ffmpeg#74]
Fribidi won't compile anymore. Package can't be downloaded. Changed the url to:

https://github.com/fribidi/fribidi/archive/${FRIBIDI_VERSION}.tar.gz

and modified the parameters, but then it complains that it can't find configure.

**Comment by jrottenberg** [comment]
ah !
instead of http://fribidi.org/download/fribidi-${FRIBIDI_VERSION}.tar.bz2 

I see, thanks. Will update, not sure why travis build passed though.

**Comment by jrottenberg** [comment]
yeah ouch : 

```
curl -I fribidi.org
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Keep-Alive: timeout=15
Date: Wed, 15 Nov 2017 22:29:15 GMT
Server: Apache
Location: https://github.com/fribidi/fribidi/
```

**Comment by jrottenberg** [comment]
closing as we pushed #75 which fixed it.
