### ISSUE TITLE
Label docker images of latest version with only the flavor name

### ISSUE THREAD

**Issue by dimrozakis** [jrottenberg/ffmpeg#76]
For example, I'm trying to reduce downloaded size, so I'll always want the `alpine` based image. Currently, to download the latest alpine based image, I have to pull `jrottenberg/ffmpeg:3.4-alpine`. I'll have to keep track of new releases and update the image tag. I'd much prefer being able to pull `jrottenberg/ffmpeg:latest-alpine` or just `jrottenberg/ffmpeg:alpine` to be always working with the latest alpine based image.

**Comment by jrottenberg** [comment]
I hear you, although I like the idea of knowing exactly what you pull, so you don't have any surprise (and it's hard to go to latest-1 if something is wrong with the latest image). 

But it is true that everybody does it, so new users expect it.

I wish dockerhub had an api to automate the build settings process, see image on https://docs.docker.com/docker-hub/builds/#add-and-run-a-new-build

With all the variants and versions we support, it is a bit painful to manage it with a mouse ;-)

I'll prepare alpine and the other variants, soon. And check with docker what they can do to automate that part...

**Comment by jrottenberg** [comment]
ok added
jrottenberg/ffmpeg:alpine
jrottenberg/ffmpeg:centos
jrottenberg/ffmpeg:scratch
on top of jrottenberg/ffmpeg:latest (ubuntu)

all based on 3.4.

They will come, dockerhub is building them...

**Comment by noplanman** [comment]
Hope it's ok to continue the thread here, as it's totally related.

I noticed that the flavour tags aren't up to date.
Arguably they should always be the very latest versions, right?

**Comment by jrottenberg** [comment]
They are not ? can you point me to one flavor tag with expected ffmpeg version, and observed one ?

**Comment by noplanman** [comment]
As an example, `ffmpeg:alpine` is from over 1 year ago (last entry on this page):
https://hub.docker.com/r/jrottenberg/ffmpeg/tags?page=2&name=alpine

It should be the same as the latest 4.3-alpine though, right?
https://hub.docker.com/r/jrottenberg/ffmpeg/tags?page=1&name=4.3-alpine

**Comment by noplanman** [comment]
Ping @jrottenberg

**Comment by jrottenberg** [comment]
You are right they are old and confusing.

I never liked `latest` or `ubuntu`,  `centos`, etc.

It's a disaster waiting to happen, when something works well with jrottenberg/docker:latest and all the sudden ffmpeg changes completely the parameters, from 3.x to 4.x , 4.x to 5.x etc.

It is convenient for a quick and dirty test, but I like the current model : pinned version (very precise `3.2.15-alpine38`) or more loose (`3.2-alpine`). Hum you are saying, what about `4-alpine`?  `4-alpine`, yeah, but no `alpine`.


Ok sold, not sure how to do it, yet but it's a fair point.

**Comment by noplanman** [comment]
Agreed! :+1:

Might be a good idea to delete the old "variant-only" tags altogether and then focus on the new scheme you suggested.

**Comment by jrottenberg** [comment]
of course I missed one step... not to be closed yet.
