### ISSUE TITLE
ffprobe -show_streams "profile" field output is numeric instead of string

### ISSUE THREAD

**Issue by jcooper-gpsw** [jrottenberg/ffmpeg#78]
Current behaviour:

```sh
# docker run -it --entrypoint=/bin/sh jrottenberg/ffmpeg:3.4
# ffprobe -v error -show_streams test.mp4 | grep profile
profile=1
profile=578
```

Expected behaviour: (ffmpeg 3.4 installed on alpine, macOS, and Ubuntu)
```sh
# ffprobe -show_streams -v error test.mp4 | grep profile
profile=LC
profile=Constrained Baseline
```

**Comment by jcooper-gpsw** [comment]
Solution: String values are enabled by building ffmpeg with `--enable-hardcoded-tables` flag.

**Comment by jrottenberg** [comment]
Oh that was fast, not sure to follow you. Should that flag be part of the build ?

**Comment by jcooper-gpsw** [comment]
@jrottenberg, I think my requirement isn't a common case, and I'm still not sure why this "fixed" the behaviour. The `ffprobe` 3.4 binary from ffmpeg.org was not built with that flag set.

**Comment by jrottenberg** [comment]
ok let us know, it would make sense to have ffprobe compiled with that flag, but leaving ffmpeg alone since it seems to impact performance.
