### ISSUE TITLE
2.7 tag no longer available on docker hub

### ISSUE THREAD

**Issue by jfairley** [jrottenberg/ffmpeg#8]
My company uses docker for developer VMs, and one of these extends `FROM jrottenberg/ffmpeg:2.7`. Today I noticed that the 2.7 tag is no longer available on docker hub. Do you know why that is? Was it removed by you, or does docker hub have an automatic expiration on old tags?

Thanks!

**Comment by jrottenberg** [comment]
Oh sorry about that, definitely not intended :


https://hub.docker.com/r/jrottenberg/ffmpeg/tags/

the 2.7 seems unavailable for some reason, I'll check with docker hub team as why.

Worst case I can branh from that git tag https://github.com/jrottenberg/ffmpeg/releases/tag/2.7 and have them rebuild.

**Comment by jrottenberg** [comment]
Ok you should have a 2.7 tag back online, 2.7.7 to precise (the latest from the 2.7 series)

I think I know what happened, the dockerfile for that image had some dependancies (libvpx) not pinned, it was a simple git clone , make & make install. Of course webm/libvpx evolved to a point that broke 2.7.
If you look at the fix, it's mostly a pinned version of libvpx to 1.3
