### ISSUE TITLE
How to exit from docker container after ffmpeg lost input stream ?

### ISSUE THREAD

**Issue by mausspb** [jrottenberg/ffmpeg#81]
I want ffmpeg reconnect to src after lost input stream, may be lets make exit from docker after lost stream and docker auto restart ?
How i can make exit from docker after lost ffmpeg src stream input ?

**Comment by jrottenberg** [comment]
For sure you can't have ffmpeg exiting out , as you'll lose the running container. It seems to support options to reconnect and be more resilient, up to a point though, see https://superuser.com/a/1050499 .

Worst case maybe add some logic on the part calling the docker run (starting the container) to intercept exit code and retry in case of failure.

**Comment by mausspb** [comment]
Solution [here](https://superuser.com/a/1284452/620897)
