### ISSUE TITLE
How do i use ffmpeg to transcode file in host machine ? for instance : docker run jrottenberg/ffmpeg:3.2-centos -i /opt/ffmpeg/resource/1.mp4

### ISSUE THREAD

**Issue by championjing** [jrottenberg/ffmpeg#85]

**Comment by jrottenberg** [comment]
Thanks @jidckii , yeah it's even part of an example in the readme : 
https://github.com/jrottenberg/ffmpeg#convert-10bits-mkv-into-a-10bits-mp4

Closing.
