### ISSUE TITLE
Q: there will be a timely update of the vpx version to 1.7.0 ?

### ISSUE THREAD

**Issue by 3qdev** [jrottenberg/ffmpeg#87]

**Comment by jrottenberg** [comment]
it was released yesterday ;-p
https://github.com/webmproject/libvpx/tags


You want to give it a try ? 
Edit https://github.com/jrottenberg/ffmpeg/blob/master/templates/Dockerfile-env#L11
run `./update.py` 
commit & push & merge request.

**Comment by jrottenberg** [comment]
thank you @3qdev 
>>> "If you want something done right, do it yourself

It's merged, if docker hub doesn't sweat too much, we should have the image with vpx 1.7 tomorrow morning.
