### ISSUE TITLE
How to implement into a different docker image?

### ISSUE THREAD

**Issue by AppleTechy** [jrottenberg/ffmpeg#90]
Hello. I am running a Homebridge Docker image and I need for it to be able to use ffmpeg. So inside the other dockerfile can I copy and paste the run code? I am fairly new to Docker , will having it install and compile for Ubuntu work in every use case scenario without having to worry about the host os that has Docker installed on it? Or is there someway for docker to pick up the host os and install the correct version of ffmpeg? Or is there some way to pull the package that is already built since this takes a long time to build?

**Comment by jrottenberg** [comment]
As far as I can see Homebridge comes with npm, so you can do it two ways : 

- start with homebridge based image you found and change my image's FROM line (replace ubuntu with the one with homebridge in it)
or 
- take my image, install npm/node and install homeridge via npm.


Let me know how that goes.

**Comment by guyhuang** [comment]
Hi:
I've tried the first way: Change the jrottenberg/ffmpeg docker file from line(replace alpine with openjdk:8 which is base on alpine). 
Here is the From phrase:
`FROM        openjdk:8 AS base`

But when I was building the image, I got the returned a non-zero code 35 error an step 23/46. Here is the error.
`Step 23/46 : RUN         DIR=/tmp/ogg &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO http://downloads.xiph.org/releases/ogg/libogg-${OGG_VERSION}.tar.gz &&         echo ${OGG_SHA256SUM} | sha256sum --check &&         tar -zx --strip-components=1 -f libogg-${OGG_VERSION}.tar.gz &&         ./configure --prefix="${PREFIX}" --enable-shared  &&         make &&         make install &&         rm -rf ${DIR} ---> Using cache ---> 986628ff6c2fStep 24/46 : RUN         DIR=/tmp/opus &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz &&         echo ${OPUS_SHA256SUM} | sha256sum --check &&         tar -zx --strip-components=1 -f opus-${OPUS_VERSION}.tar.gz &&         autoreconf -fiv &&         ./configure --prefix="${PREFIX}" --enable-shared &&         make &&         make install &&         rm -rf ${DIR} ---> Running in 521c3d92062fThe command '/bin/sh -c DIR=/tmp/opus &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz &&         echo ${OPUS_SHA256SUM} | sha256sum --check &&         tar -zx --strip-components=1 -f opus-${OPUS_VERSION}.tar.gz &&         autoreconf -fiv &&         ./configure --prefix="${PREFIX}" --enable-shared &&         make &&         make install &&         rm -rf ${DIR}' returned a non-zero code: 35`

**Comment by maisun** [comment]
> Hello. I am running a Homebridge Docker image and I need for it to be able to use ffmpeg. So inside the other dockerfile can I copy and paste the run code? I am fairly new to Docker , will having it install and compile for Ubuntu work in every use case scenario without having to worry about the host os that has Docker installed on it? Or is there someway for docker to pick up the host os and install the correct version of ffmpeg? Or is there some way to pull the package that is already built since this takes a long time to build?

Hi, any luck to get this working with homebridge?
