### ISSUE TITLE
Add gpac (MP4box)

### ISSUE THREAD

**Issue by jidckii** [jrottenberg/ffmpeg#93]
Hello!

Add the GPAC package
https://github.com/gpac/gpac
It is very useful for generating MPD manifests for DASH.

**Comment by jrottenberg** [comment]
Yeah I was wondering about that one or bento4...

It's not strictly required by ffmpeg, there's many tools that work very well with ffmpeg, I'd say for gpac or bento4, those should be installed separately , using this image as FROM.

**Comment by jidckii** [comment]
And why do not you want to include gpac in the current assembly?
It takes up little space, but it will be very convenient to have everything in one place at once.
Simply replacing the endrtypoint if necessary with mp4box.
In any case, you decide))

If you think that there should be a separate image, it would be cool if you prepare such images.
I'm very pleased with the freshness and quality of your assemblies.
Thanks for the work you've done ))
