### ISSUE TITLE
Synology Theroa compilation pb

### ISSUE THREAD

**Issue by fbarret** [jrottenberg/ffmpeg#95]
Hello
I am trying to compile your Dockerfile on my Synology but Im'getting this error:
checking pkg-config is at least version 0.9.0... yes
checking for OGG... no
checking for Ogg... no
*** Could not run Ogg test program, checking why...
*** The test program failed to compile or link. See the file config.log for the
*** exact error that occured. This usually means Ogg was incorrectly installed
*** or that you have moved Ogg since it was installed.
configure: error:
    libogg is required to build this package!
    please see http://www.xiph.org/ for how to
    obtain a copy.

The command '/bin/sh -c DIR=/tmp/theora &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO http://downloads.xiph.org/releases/theora/libtheora-${THEORA_VERSION}.tar.gz &&         tar -zx --strip-components=1 -f libtheora-${THEORA_VERSION}.tar.gz &&         ./configure --prefix="${PREFIX}" --with-ogg="${PREFIX}" --enable-shared &&         make &&         make install &&         rm -rf ${DIR}' returned a non-zero code: 1

Do you know why?

**Comment by jrottenberg** [comment]
I'm curious to see your dockerfile, but yeah it fails on theora, it needs libogg.

did you add that part? can you share the dockerfile you're using ?

**Comment by fbarret** [comment]
Hello

here is my Dockerfile. IT is based on your Alpine 3.4's Dockerfile image.
Since I posted the issue I moved the compilation of Theora at the end of the Dockerfile to check the other compilations. I got this new error in fontconfig compilation:

checking The type of len parameter of gperf hash/lookup function... unsigned int
checking for FREETYPE... no
configure: error: Package requirements (freetype2) were not met:

Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'freetype2', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
The command '/bin/sh -c DIR=/tmp/fontconfig &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLO https://www.freedesktop.org/software/fontconfig/release/fontconfig-${FONTCONFIG_VERSION}.tar.bz2 &&        tar -jx --strip-components=1 -f fontconfig-${FONTCONFIG_VERSION}.tar.bz2 &&         ./configure -prefix="${PREFIX}" --disable-static --enable-shared &&         make &&         make install &&         rm -rf ${DIR}' returned a non-zero code: 1

Thank you 
Best Regards
as .txt:
[Dockerfile.txt](https://github.com/jrottenberg/ffmpeg/files/1754297/Dockerfile.txt)

**Comment by fbarret** [comment]
.

**Comment by jrottenberg** [comment]
fontconfig requires freetype, somehow freetype is not in your dockerfile, put it back _before_ fontconfig

**Comment by jrottenberg** [comment]
yeah somehow it could not find freetype, but it's supposed to be compiled before, let me check locally.

**Comment by jrottenberg** [comment]
seems to work after a retry ?!?

it would have failed on pip anyway, try  : https://gist.github.com/jrottenberg/07012b91eee2b9806c0787ca87943fe0

**Comment by resgroupmsr** [comment]
I'm trying to get ffmpeg running properly in homebridge on my Synology NAS.  I've tried everything that makes sense.  When running your install in Docker on the Synology it starts up then immediately crashes.  Any ideas?
