### ISSUE TITLE
Saving output into AWS S3

### ISSUE THREAD

**Issue by lukaszmalec6** [jrottenberg/ffmpeg#98]
Hello, is it possible to provide simple example of saving transcoding output into AWS S3 Bucket?
It would be superusefull. Thank you! :)

**Comment by scottveirs** [comment]
@lukaszmalec6 

We have a working prototype that uses rsync and s3fs to transfer HLS segments and FLAC files to S3 buckets -- https://github.com/orcasound/orcanode/blob/master/stream.sh

We are working on a Python script that will use inotify and boto to optimize upload for live-streaming -- https://github.com/orcasound/orcanode/blob/s3_upload/upload_s3.py

**Comment by jrottenberg** [comment]
@lukaszmalec6 let me know if you need more example, but to be fair it's more ffmpeg specific than a docker + ffmpeg question.
