### ISSUE TITLE
Multi-stage docker builds

### ISSUE THREAD

**Issue by jmgirven** [jrottenberg/ffmpeg#99]
Would it be possible to create a set of images where FFmpeg is not dynamically linked to its shared libraries? My reasoning is that then you could use docker's multi-stage build process to simply copy the FFmpeg / FFprobe binaries out of this container and into any other container. E.g:

```
FROM jrottenberg/ffmpeg AS ffmpeg

FROM python

# Copy in FFmpeg and FFprobe
COPY --from=ffmpeg /usr/local/bin/ffmpeg /usr/local/bin/
```

Currently doing this means calls to FFmpeg give the message

```
ffmpeg: error while loading shared libraries: libavdevice.so.57: cannot open shared object file: No such file or directory
```

It would be a nice alternative to changing the `FROM` as suggested #90 .

I'm sure this is much more complicated than I am imagining!

**Comment by Oliboy50** [comment]
I also experienced issues with this... I'd hope it would work as expected

**Comment by vagari** [comment]
I could have sworn I found a more straightforward method, but a while back I had some success with using `LD_LIBRARY_PATH` to copy over all the files to the new container _and_ link them back up. I'll try to dig up the references when I have some time, but maybe this pointer will be enough to get you started down the right path...

**Comment by Oliboy50** [comment]
I tested every available distrib for 4.0 and 3.4... but I didn't managed to get the binary working in the final image

- using `ubuntu` based image I had the same OP error message

- using others based image (including `scratch`), my binary didn't want to execute at all (something like `ffmpeg command was not found`) even after `chmod a+rx` the binary, etc.

I didn't try @vagari solution thought

what I did after losing a lot of time was simply installing ffmpeg in my final image 😞:
```Dockerfile
FROM node:8.11.2-stretch

RUN apt-get update && apt-get install -y libav-tools ffmpeg
```

**Comment by adampl** [comment]
This is how I managed to have both Python 3.6 and FFmpeg in one image:

```dockerfile
FROM jrottenberg/ffmpeg:4.0-scratch AS ffmpeg
FROM python:3.6
COPY --from=ffmpeg / /
```

**Comment by chriswiggins** [comment]
To add to this, we're using the following in our production Dockerfiles:

```
ENV LD_LIBRARY_PATH=/usr/local/lib
COPY --from=jrottenberg/ffmpeg /usr/local /usr/local/
```

Works well 👍

**Comment by leandromoreira** [comment]
I think it'd be nice to have intermediate images for development, I shameless did (copy & change) an [ffmpeg-devel image](https://github.com/leandromoreira/ffmpeg-libav-tutorial/blob/master/Dockerfile) already posted to [dockerhub](https://hub.docker.com/r/leandromoreira/ffmpeg-devel/).

With this image you can create, test, compile and run your ffmpeg programs:

```Makefile
clean:
	@rm -rf ./build/*

make_hello: clean
	docker run --rm -it -v `pwd`:/files leandromoreira/ffmpeg-devel \
	  gcc -L/opt/ffmpeg/lib -I/opt/ffmpeg/include/ /files/MYCODE.c \
	  -lavcodec -lavformat -lavfilter -lavdevice -lswresample -lswscale -lavutil \
	  -o /files/build/MYPROGRAM

run_hello: make_hello
	docker run --rm -it -v `pwd`:/files leandromoreira/ffmpeg-devel /files/build/MYPROGRAM /files/small_bunny_1080p_60fps.mp4

```

**Comment by jrottenberg** [comment]
it exists now : https://github.com/videotools/ffmpeg-build

**Comment by GZaccaroni** [comment]
> To add to this, we're using the following in our production Dockerfiles:
> 
> ```
> ENV LD_LIBRARY_PATH=/usr/local/lib
> COPY --from=jrottenberg/ffmpeg /usr/local /usr/local/
> ```
> 
> Works well 👍

With ubuntu20.04 and ffmpeg 20.04-ubuntu it is no longer working. I get the following error:

```
ffmpeg: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by cake808** [comment]
For me the suggested solutions didn't work, but they helped me finding a working solution :slightly_smiling_face: 

```
FROM jrottenberg/ffmpeg:4.3-scratch312 AS ffmpeg
COPY --from=ffmpeg / /
```

**Comment by washcroft** [comment]
Copying the entire image into your destination can sometimes causes problems, this also works:

```
ENV LD_LIBRARY_PATH=/usr/local/lib
COPY --from=ffmpeg /usr/local /usr/local
COPY --from=ffmpeg /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
```

**Comment by Bobronium** [comment]
This is how I got it to work. Leaving it here since this is the only result I found when googling for multistage builds with ffmpeg.

## Complete Dockerfile
```dockerfile
FROM debian:buster-slim as base  # replace with your actual base image, e.g. `python-slim`

FROM base as base-installer
RUN apt update

FROM base-installer as ffmpeg-installer
RUN apt install --no-install-recommends -y ffmpeg

FROM base as runtime
COPY --from=ffmpeg-installer /usr/bin/ffmpeg /usr/bin/ffmpeg
COPY --from=ffmpeg-installer /usr/lib/*-linux-gnu/* /usr/lib/
COPY --from=ffmpeg-installer /lib/*-linux-gnu/* /usr/lib/
```

## How to get ffmpeg for any image
1. Define stage where you have working ffmpeg (in this example I install it with apt, but you can use ffmpeg as base image):
    ```dockerfile
    FROM debian:buster-slim as base  # replace with your actual base image, e.g. `python-slim`
    
    FROM base as base-installer
    RUN apt update
    
    FROM base-installer as ffmpeg-installer
    RUN apt install --no-install-recommends -y ffmpeg
    ```
2. Verify that at this stage ffmpeg is indeed working:
    ```shell
    docker build --target ffmpeg-installer . -t ffmpeg
    docker run -it ffmpeg ffmpeg
    ```
3. Get path where ffmpeg is installed:
    ```shell
    docker run -it ffmpeg which ffmpeg
    # /usr/bin/ffmpeg
    ```
4. Add ffmpeg binary to your runtime stage:
    ```dockerfile
    FROM base as runtime
    COPY --from=ffmpeg-installer /usr/bin/ffmpeg /usr/bin/ffmpeg
    ```
5. Run ffmpeg from your runtime target and observe the error (or success!):
    ```shell
    docker build --target runtime -t runtime .
    docker run -it runtime ffmpeg
    # ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory
    ```
6. Find location of shared library in ffmpeg-installer target:
    ```shell
    docker run -it ffmpeg find / -name libavdevice.so.58      
    # /usr/lib/aarch64-linux-gnu/libavdevice.so.58
    ```
7. Copy the lib location to your runtime stage (note * instead of arch name, this will work with multiarch builds):
    ```dockerfile
    FROM base as runtime
    COPY --from=ffmpeg-installer /usr/bin/ffmpeg /usr/bin/ffmpeg
    COPY --from=builder-base /usr/lib/*-linux-gnu/* /usr/lib/
    ```
8. Return to 5. untill you don't observe errors anymore (took 1 repeat for me).

**Comment by geminixiang** [comment]
Thank you guys, and here is an updated solution for combining Alpine and Debian docker image~

```dockerfile
# stage1: based on alpine
FROM jrottenberg/ffmpeg:6.0-scratch as ffmpeg

# stage2: based on debian
FROM python:3.10.8-slim AS base  
COPY --from=ffmpeg /bin/ffmpeg /bin/ffprobe /usr/local/bin/
COPY --from=ffmpeg /lib /lib
COPY --from=ffmpeg /share /share
```
